version: '3'
name: airflow

services:

  docker-proxy:
    image: docker:24-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - airflow-data-volume:/data

  airflow-scheduler:
    extends:
      file: airflow/docker-compose.yaml
      service: airflow-scheduler

  airflow-webserver:
    extends:
      file: airflow/docker-compose.yaml
      service: airflow-webserver

  airflow-worker:
    extends:
      file: airflow/docker-compose.yaml
      service: airflow-worker

  airflow-triggerer:
    extends:
      file: airflow/docker-compose.yaml
      service: airflow-triggerer

  airflow-init:
    extends:
      file: airflow/docker-compose.yaml
      service: airflow-init

  postgres:
    extends:
      file: airflow/docker-compose.yaml
      service: postgres

  redis:
    extends:
      file: airflow/docker-compose.yaml
      service: redis

volumes:
  postgres-db-volume:

networks:
  default: 
    external: true
    name: data-engineering-labs-network
