version: '3'

services:
  apache-nifi:
    image: apache/nifi:1.23.2
    environment:
      - NIFI_WEB_HTTP_PORT=18080
      - NIFI_WEB_HTTP_HOST=0.0.0.0
      - NIFI_WEB_HTTPS_PORT=
      - NIFI_WEB_HTTPS_HOST=
    volumes:
      - ./nifi/drivers:/opt/nifi/nifi-current/drivers
      - ./nifi/templates:/opt/nifi/nifi-current/templates
      - ./nifi/data:/opt/nifi/nifi-current/data
    ports:
      - 18080:18080

  elasticsearch-kibana:
    image: nshou/elasticsearch-kibana:kibana7
    ports:
      - 19200:9200
      - 15601:5601

  airflow-scheduler:
    extends:
      file: airflow/docker-compose.yaml
      service: airflow-scheduler

  airflow-webserver:
    extends:
      file: airflow/docker-compose.yaml
      service: airflow-webserver

  airflow-worker:
    extends:
      file: airflow/docker-compose.yaml
      service: airflow-worker

  airflow-triggerer:
    extends:
      file: airflow/docker-compose.yaml
      service: airflow-triggerer

  airflow-init:
    extends:
      file: airflow/docker-compose.yaml
      service: airflow-init

  postgres:
    extends:
      file: airflow/docker-compose.yaml
      service: postgres

  redis:
    extends:
      file: airflow/docker-compose.yaml
      service: redis

  flower:
    extends:
      file: airflow/docker-compose.yaml
      service: flower

  postgresql-standalone:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: workspace
    volumes:
      - postgres-db-workspace-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      retries: 5
      start_period: 5s

  adminer:
    image: dpage/pgadmin4:7.6
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgresql-standalone
    ports:
      - 18081:80

volumes:
  postgres-db-volume:
  postgres-db-workspace-volume: